import DesolateForest1 from '../../resources/Stage1/DesolateForest1.png';
import DesolateForest2 from '../../resources/Stage1/DesolateForest2.png';
import DesolateForest3 from '../../resources/Stage1/DesolateForest3.png';
import DesolateForest4 from '../../resources/Stage1/DesolateForest4.png';
import DesolateForest5 from '../../resources/Stage1/DesolateForest5.png';
import DesolateForest6 from '../../resources/Stage1/DesolateForest6.png';
import DriedLake1 from '../../resources/Stage1/DriedLake1.png';
import DriedLake2 from '../../resources/Stage1/DriedLake2.png';
import DriedLake3 from '../../resources/Stage1/DriedLake3.png';
import DriedLake4 from '../../resources/Stage1/DriedLake4.png';
import DriedLake5 from '../../resources/Stage1/DriedLake5.png';
import DriedLake6 from '../../resources/Stage1/DriedLake6.png';
import DampCaverns1 from '../../resources/Stage2/DampCaverns1.png';
import DampCaverns2 from '../../resources/Stage2/DampCaverns2.png';
import DampCaverns3 from '../../resources/Stage2/DampCaverns3.png';
import DampCaverns4 from '../../resources/Stage2/DampCaverns4.png';
import DampCaverns5 from '../../resources/Stage2/DampCaverns5.png';
import DampCaverns6 from '../../resources/Stage2/DampCaverns6.png';
import SkyMeadows1 from '../../resources/Stage2/SkyMeadows1.png';
import SkyMeadows2 from '../../resources/Stage2/SkyMeadows2.png';
import SkyMeadows3 from '../../resources/Stage2/SkyMeadows3.png';
import SkyMeadows4 from '../../resources/Stage2/SkyMeadows4.png';
import SkyMeadows5 from '../../resources/Stage2/SkyMeadows5.png';
import SkyMeadows6 from '../../resources/Stage2/SkyMeadows6.png';
import AncientValley1 from '../../resources/Stage3/AncientValley1.png';
import AncientValley2 from '../../resources/Stage3/AncientValley2.png';
import AncientValley3 from '../../resources/Stage3/AncientValley3.png';
import AncientValley4 from '../../resources/Stage3/AncientValley4.png';
import AncientValley5 from '../../resources/Stage3/AncientValley5.png';
import AncientValley6 from '../../resources/Stage3/AncientValley6.png';
import SunkenTombs1 from '../../resources/Stage3/SunkenTombs1.png';
import SunkenTombs2 from '../../resources/Stage3/SunkenTombs2.png';
import SunkenTombs3 from '../../resources/Stage3/SunkenTombs3.png';
import SunkenTombs4 from '../../resources/Stage3/SunkenTombs4.png';
import SunkenTombs5 from '../../resources/Stage3/SunkenTombs5.png';
import SunkenTombs6 from '../../resources/Stage3/SunkenTombs6.png';
import HiveCluster1 from '../../resources/Stage4/HiveCluster1.png';
import HiveCluster2 from '../../resources/Stage4/HiveCluster2.png';
import HiveCluster3 from '../../resources/Stage4/HiveCluster3.png';
import HiveCluster4 from '../../resources/Stage4/HiveCluster4.png';
import HiveCluster5 from '../../resources/Stage4/HiveCluster5.png';
import HiveCluster6 from '../../resources/Stage4/HiveCluster6.png';
import MagmaBarracks1 from '../../resources/Stage4/MagmaBarracks1.png';
import MagmaBarracks2 from '../../resources/Stage4/MagmaBarracks2.png';
import MagmaBarracks3 from '../../resources/Stage4/MagmaBarracks3.png';
import MagmaBarracks4 from '../../resources/Stage4/MagmaBarracks4.png';
import MagmaBarracks5 from '../../resources/Stage4/MagmaBarracks5.png';
import MagmaBarracks6 from '../../resources/Stage4/MagmaBarracks6.png';
import TempleOfTheElders1 from '../../resources/Stage5/TempleOfTheElders1.png';
import TempleOfTheElders2 from '../../resources/Stage5/TempleOfTheElders2.png';
import TempleOfTheElders3 from '../../resources/Stage5/TempleOfTheElders3.png';
import TempleOfTheElders4 from '../../resources/Stage5/TempleOfTheElders4.png';
import TempleOfTheElders5 from '../../resources/Stage5/TempleOfTheElders5.png';
import TempleOfTheElders6 from '../../resources/Stage5/TempleOfTheElders6.png';
import RiskOfRain1 from '../../resources/Stage6/RiskOfRain1.png';
import RiskOfRain2 from '../../resources/Stage6/RiskOfRain2.png';



export const DesolateForestVariants = [DesolateForest1, DesolateForest2, DesolateForest3, DesolateForest4, DesolateForest5, DesolateForest6];
export const DriedLakeVariants = [DriedLake1, DriedLake2, DriedLake3, DriedLake4, DriedLake5, DriedLake6];
export const DampCavernsVariants = [DampCaverns1, DampCaverns2, DampCaverns3, DampCaverns4, DampCaverns5, DampCaverns6];
export const SkyMeadowsVariants = [SkyMeadows1, SkyMeadows2, SkyMeadows3, SkyMeadows4, SkyMeadows5, SkyMeadows6];
export const AncientValleyVariants = [AncientValley1, AncientValley2, AncientValley3, AncientValley4, AncientValley5, AncientValley6];
export const SunkenTombsVariants = [SunkenTombs1, SunkenTombs2, SunkenTombs3, SunkenTombs4, SunkenTombs5, SunkenTombs6];
export const HiveClusterVariants = [HiveCluster1, HiveCluster2, HiveCluster3, HiveCluster4, HiveCluster5, HiveCluster6];
export const MagmaBarracksVariants = [MagmaBarracks1, MagmaBarracks2, MagmaBarracks3, MagmaBarracks4, MagmaBarracks5, MagmaBarracks6];
export const TempleOfTheEldersVariants = [TempleOfTheElders1, TempleOfTheElders2, TempleOfTheElders3, TempleOfTheElders4, TempleOfTheElders5, TempleOfTheElders6];
export const RiskOfRainVariants = [RiskOfRain1, RiskOfRain2];